In [1]:
import pandas as pd
df = pd.read_csv('Airlines Reviews and Rating.csv')
df.head()

,Aircraft Type,Users Reviews,Country,Type_of_Travellers,Route,Seat_Types,Seat Comfort,Date Flown,Cabin Staff Service,Ground Service,Food & Beverages,Wifi & Connectivity,Inflight Entertainment,Value For Money,Recommended
0,NaN,✅Trip Verified| Cancelled our flight last-min...,United Kingdom,Couple Leisure,London Heathrow to Tokyo,Economy Class,1.0,Sep-23,1.0,2.0,1.0,NaN,3.0,1,no
1,NaN,"✅Trip Verified| I had a flight from Miami, Flo...",United States,Solo Leisure,Miami to Dublin via London Heathrow,Business Class,1.0,Aug-23,3.0,1.0,2.0,1.0,1.0,1,no
2,NaN,✅Trip Verified| We started our day with BA in...,United States,Business,Prague to San Francisco via London,Business Class,1.0,Sep-23,3.0,1.0,3.0,1.0,NaN,1,no
3,NaN,✅Trip Verified| I fly British Airways weekly ...,United Kingdom,Business,London to Glasgow,Economy Class,1.0,Sep-23,1.0,1.0,1.0,1.0,1.0,1,no
4,NaN,Not Verified| Everything was ok until our con...,France,Family Leisure,San Diego to Marseille via London,Economy Class,3.0,Aug-23,2.0,1.0,3.0,1.0,3.0,3,no

In [2]:
df.drop(
    [
       'Aircraft Type', 'Users Reviews','Country', 'Route', 'Date Flown'],  
    axis=1, inplace=True
    )

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3290 entries, 0 to 3289
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Type_of_Travellers      2887 non-null   object
 1   Seat_Types              3287 non-null   object
 2   Seat Comfort            3176 non-null   float64
 3   Cabin Staff Service     3165 non-null   float64
 4   Ground Service          2812 non-null   float64
 5   Food & Beverages        2911 non-null   float64
 6   Wifi & Connectivity     592 non-null    float64
 7   Inflight Entertainment  2171 non-null   float64
 8   Value For Money         3290 non-null   int64
 9   Recommended             3290 non-null   object
dtypes: float64(6), int64(1), object(3)
memory usage: 257.2+ KB

In [3]:
import numpy as np
data=df.apply(lambda x: x.fillna(np.random.choice(x.dropna())), axis=0)
data.head()

,Type_of_Travellers,Seat_Types,Seat Comfort,Cabin Staff Service,Ground Service,Food & Beverages,Wifi & Connectivity,Inflight Entertainment,Value For Money,Recommended
0,Couple Leisure,Economy Class,1.0,1.0,2.0,1.0,1.0,3.0,1,no
1,Solo Leisure,Business Class,1.0,3.0,1.0,2.0,1.0,1.0,1,no
2,Business,Business Class,1.0,3.0,1.0,3.0,1.0,3.0,1,no
3,Business,Economy Class,1.0,1.0,1.0,1.0,1.0,1.0,1,no
4,Family Leisure,Economy Class,3.0,2.0,1.0,3.0,1.0,3.0,3,no

In [4]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

columns_to_encode = ["Type_of_Travellers","Seat_Types","Seat Comfort","Cabin Staff Service",
                    "Ground Service","Food & Beverages","Wifi & Connectivity","Inflight Entertainment",
                    "Value For Money", "Recommended" ]

for column in columns_to_encode:
    data[column] = label_encoder.fit_transform(data[column])

data.head()

,Type_of_Travellers,Seat_Types,Seat Comfort,Cabin Staff Service,Ground Service,Food & Beverages,Wifi & Connectivity,Inflight Entertainment,Value For Money,Recommended
0,1,1,0,0,1,1,0,3,0,0
1,3,0,0,2,0,2,0,1,0,0
2,0,0,0,2,0,3,0,3,0,0
3,0,1,0,0,0,1,0,1,0,0
4,2,1,2,1,0,3,0,3,2,0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3290 entries, 0 to 3289
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Type_of_Travellers      3290 non-null   int32
 1   Seat_Types              3290 non-null   int32
 2   Seat Comfort            3290 non-null   int64
 3   Cabin Staff Service     3290 non-null   int64
 4   Ground Service          3290 non-null   int64
 5   Food & Beverages        3290 non-null   int64
 6   Wifi & Connectivity     3290 non-null   int64
 7   Inflight Entertainment  3290 non-null   int64
 8   Value For Money         3290 non-null   int64
 9   Recommended             3290 non-null   int32
dtypes: int32(3), int64(7)
memory usage: 218.6 KB

In [6]:
X = data.drop('Recommended', axis=1)
X

,Type_of_Travellers,Seat_Types,Seat Comfort,Cabin Staff Service,Ground Service,Food & Beverages,Wifi & Connectivity,Inflight Entertainment,Value For Money
0,1,1,0,0,1,1,0,3,0
1,3,0,0,2,0,2,0,1,0
2,0,0,0,2,0,3,0,3,0
3,0,1,0,0,0,1,0,1,0
4,2,1,2,1,0,3,0,3,2
...,...,...,...,...,...,...,...,...,...
3285,0,0,2,1,1,1,0,3,1
3286,0,0,3,4,1,5,0,5,3
3287,0,0,2,0,1,1,0,2,0
3288,0,0,4,4,1,4,0,4,3
3289,0,0,0,0,1,1,0,1,0

In [7]:
y = data['Recommended']
y

0       0
1       0
2       0
3       0
4       0
       ..
3285    0
3286    1
3287    0
3288    1
3289    0
Name: Recommended, Length: 3290, dtype: int32

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train

,Type_of_Travellers,Seat_Types,Seat Comfort,Cabin Staff Service,Ground Service,Food & Beverages,Wifi & Connectivity,Inflight Entertainment,Value For Money
69,2,1,0,0,0,3,0,3,0
2984,0,1,0,3,1,1,0,3,1
2878,3,0,3,4,1,2,0,4,4
1898,0,0,1,2,1,1,0,2,0
436,3,1,0,0,0,3,0,3,0
...,...,...,...,...,...,...,...,...,...
1095,3,0,2,3,4,3,0,3,3
1130,3,1,1,2,3,3,0,4,3
1294,3,3,0,2,1,4,0,1,0
860,1,0,4,4,4,5,0,5,4
3174,0,1,2,2,1,4,0,1,2

In [9]:
X_train

,Type_of_Travellers,Seat_Types,Seat Comfort,Cabin Staff Service,Ground Service,Food & Beverages,Wifi & Connectivity,Inflight Entertainment,Value For Money
69,2,1,0,0,0,3,0,3,0
2984,0,1,0,3,1,1,0,3,1
2878,3,0,3,4,1,2,0,4,4
1898,0,0,1,2,1,1,0,2,0
436,3,1,0,0,0,3,0,3,0
...,...,...,...,...,...,...,...,...,...
1095,3,0,2,3,4,3,0,3,3
1130,3,1,1,2,3,3,0,4,3
1294,3,3,0,2,1,4,0,1,0
860,1,0,4,4,4,5,0,5,4
3174,0,1,2,2,1,4,0,1,2

In [10]:
X_test

,Type_of_Travellers,Seat_Types,Seat Comfort,Cabin Staff Service,Ground Service,Food & Beverages,Wifi & Connectivity,Inflight Entertainment,Value For Money
1407,0,3,0,2,3,1,0,3,3
3159,0,0,3,3,1,4,0,4,3
1926,1,1,2,4,2,5,0,4,3
3173,0,0,0,2,1,2,0,3,1
1345,1,0,3,3,3,4,0,3,3
...,...,...,...,...,...,...,...,...,...
1025,3,2,4,4,4,4,0,4,4
802,2,1,4,4,4,5,4,1,4
2775,1,1,0,0,0,1,0,2,0
839,0,1,3,2,0,2,0,3,2
817,1,1,0,2,3,1,0,1,2

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
X_train

array([[ 0.56322425,  0.047127  , -1.38734415, ..., -0.23734681,
         0.21235963, -1.12245695],
       [-1.14167078,  0.047127  , -1.38734415, ..., -0.23734681,
         0.21235963, -0.43779723],
       [ 1.41567177, -1.09083869,  0.82210914, ..., -0.23734681,
         1.08842631,  1.61618193],
       ...,
       [ 1.41567177,  2.32305837, -1.38734415, ..., -0.23734681,
        -1.53977373, -1.12245695],
       [-0.28922326, -1.09083869,  1.55859357, ..., -0.23734681,
         1.96449298,  1.61618193],
       [-1.14167078,  0.047127  ,  0.08562471, ..., -0.23734681,
        -1.53977373,  0.24686249]])

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical

In [14]:
giris_katmani = X_train.shape[1]
print(f"input_dim: {giris_katmani}")

output_dim = y_train.nunique()
print(f"output_dim: {output_dim}")

model = Sequential()

model.add(Dense(128, input_dim=giris_katmani, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

input_dim: 9
output_dim: 2

c:\Users\asus\Desktop\YapayZeka\derin_ogrenme\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [15]:
model.summary() # modelin özeti

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │         1,280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,593 (41.38 KB)

 Trainable params: 10,593 (41.38 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

In [17]:
model.fit(X_train, y_train, epochs=150, batch_size=25, validation_data=(X_test, y_test))

Epoch 1/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9038 - loss: 0.3205 - val_accuracy: 0.9149 - val_loss: 0.1999
Epoch 2/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9331 - loss: 0.1787 - val_accuracy: 0.9119 - val_loss: 0.1983
Epoch 3/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9259 - loss: 0.1761 - val_accuracy: 0.9119 - val_loss: 0.2103
Epoch 4/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9480 - loss: 0.1488 - val_accuracy: 0.9119 - val_loss: 0.2086
Epoch 5/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9309 - loss: 0.1734 - val_accuracy: 0.9134 - val_loss: 0.1971
Epoch 6/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9367 - loss: 0.1707 - val_accuracy: 0.9195 - val_loss: 0.2024
Epoch 7/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9268 - loss: 0.1657 - val_accuracy: 0.9164 - val_loss: 0.2123
Epoch 8/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9328 - loss: 0.1678 - val_accuracy: 0.9164 - val_loss: 0.2054
Epoch 9/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9429 - loss: 0.1549 - val_accuracy: 0.9210 - val_loss: 0.2018
Epoch 10/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9512 - loss: 0.1480 - val_accuracy: 0.9179 - val_loss: 0.1964
Epoch 11/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9478 - loss: 0.1424 - val_accuracy: 0.9195 - val_loss: 0.1963
Epoch 12/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9487 - loss: 0.1441 - val_accuracy: 0.9240 - val_loss: 0.2012
Epoch 13/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9417 - loss: 0.1471 - val_accuracy: 0.9225 - val_loss: 0.1982
Epoch 14/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9531 - loss: 0.1299 - val_accuracy: 0.9195 - val_loss: 0.1984
Epoch 15/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9459 - loss: 0.1512 - val_accuracy: 0.9225 - val_loss: 0.2037
Epoch 16/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9491 - loss: 0.1435 - val_accuracy: 0.9195 - val_loss: 0.2033
Epoch 17/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9514 - loss: 0.1356 - val_accuracy: 0.9225 - val_loss: 0.2024
Epoch 18/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9482 - loss: 0.1345 - val_accuracy: 0.9240 - val_loss: 0.2088
Epoch 19/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9540 - loss: 0.1326 - val_accuracy: 0.9255 - val_loss: 0.2133
Epoch 20/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9570 - loss: 0.1223 - val_accuracy: 0.9179 - val_loss: 0.2104
Epoch 21/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9549 - loss: 0.1361 - val_accuracy: 0.9225 - val_loss: 0.2126
Epoch 22/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9538 - loss: 0.1197 - val_accuracy: 0.9134 - val_loss: 0.2169
Epoch 23/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9509 - loss: 0.1304 - val_accuracy: 0.9301 - val_loss: 0.2137
Epoch 24/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9592 - loss: 0.1244 - val_accuracy: 0.9058 - val_loss: 0.2276
Epoch 25/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9624 - loss: 0.1091 - val_accuracy: 0.9012 - val_loss: 0.2576
Epoch 26/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9565 - loss: 0.1214 - val_accuracy: 0.9286 - val_loss: 0.2212
Epoch 27/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9584 - loss: 0.1291 - val_accuracy: 0.9119 - val_loss: 0.2331
Epoch 28/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9614 - loss: 0.1093 - val_accuracy: 0.9195 - val_loss: 0.2280
Epoch 29/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9594 - loss: 0.1121 - val_accuracy: 0.9240 - val_loss: 0.2346
Epoch 30/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9618 - loss: 0.1031 - val_accuracy: 0.9210 - val_loss: 0.2314
Epoch 31/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9650 - loss: 0.1014 - val_accuracy: 0.9210 - val_loss: 0.2405
Epoch 32/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9690 - loss: 0.0995 - val_accuracy: 0.9225 - val_loss: 0.2497
Epoch 33/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9580 - loss: 0.1094 - val_accuracy: 0.9210 - val_loss: 0.2641
Epoch 34/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9625 - loss: 0.1015 - val_accuracy: 0.9225 - val_loss: 0.2496
Epoch 35/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9641 - loss: 0.0903 - val_accuracy: 0.9255 - val_loss: 0.2441
Epoch 36/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9663 - loss: 0.0999 - val_accuracy: 0.9149 - val_loss: 0.2740
Epoch 37/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9695 - loss: 0.0875 - val_accuracy: 0.9164 - val_loss: 0.2597
Epoch 38/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9668 - loss: 0.0961 - val_accuracy: 0.9195 - val_loss: 0.2778
Epoch 39/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9694 - loss: 0.0812 - val_accuracy: 0.9058 - val_loss: 0.2728
Epoch 40/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9669 - loss: 0.0901 - val_accuracy: 0.9043 - val_loss: 0.2844
Epoch 41/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9727 - loss: 0.0815 - val_accuracy: 0.9043 - val_loss: 0.2789
Epoch 42/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9692 - loss: 0.0903 - val_accuracy: 0.9210 - val_loss: 0.3062
Epoch 43/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9703 - loss: 0.0884 - val_accuracy: 0.9088 - val_loss: 0.3078
Epoch 44/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9734 - loss: 0.0778 - val_accuracy: 0.9088 - val_loss: 0.2900
Epoch 45/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9775 - loss: 0.0675 - val_accuracy: 0.9103 - val_loss: 0.2919
Epoch 46/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9731 - loss: 0.0741 - val_accuracy: 0.9149 - val_loss: 0.3266
Epoch 47/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9691 - loss: 0.0840 - val_accuracy: 0.9058 - val_loss: 0.3164
Epoch 48/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9761 - loss: 0.0644 - val_accuracy: 0.9103 - val_loss: 0.3318
Epoch 49/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9747 - loss: 0.0635 - val_accuracy: 0.9195 - val_loss: 0.3380
Epoch 50/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9754 - loss: 0.0719 - val_accuracy: 0.9073 - val_loss: 0.3467
Epoch 51/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9759 - loss: 0.0613 - val_accuracy: 0.9103 - val_loss: 0.3573
Epoch 52/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9810 - loss: 0.0568 - val_accuracy: 0.9088 - val_loss: 0.3665
Epoch 53/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9782 - loss: 0.0599 - val_accuracy: 0.9179 - val_loss: 0.3667
Epoch 54/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9759 - loss: 0.0677 - val_accuracy: 0.9058 - val_loss: 0.3634
Epoch 55/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9791 - loss: 0.0581 - val_accuracy: 0.8997 - val_loss: 0.3835
Epoch 56/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9818 - loss: 0.0538 - val_accuracy: 0.9043 - val_loss: 0.4286
Epoch 57/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9775 - loss: 0.0640 - val_accuracy: 0.9058 - val_loss: 0.3862
Epoch 58/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9756 - loss: 0.0665 - val_accuracy: 0.9073 - val_loss: 0.4111
Epoch 59/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9789 - loss: 0.0523 - val_accuracy: 0.9088 - val_loss: 0.4344
Epoch 60/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9809 - loss: 0.0615 - val_accuracy: 0.9195 - val_loss: 0.3888
Epoch 61/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9754 - loss: 0.0605 - val_accuracy: 0.9149 - val_loss: 0.4621
Epoch 62/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9769 - loss: 0.0522 - val_accuracy: 0.9088 - val_loss: 0.4679
Epoch 63/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9779 - loss: 0.0528 - val_accuracy: 0.9134 - val_loss: 0.4611
Epoch 64/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9852 - loss: 0.0436 - val_accuracy: 0.9043 - val_loss: 0.4415
Epoch 65/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9871 - loss: 0.0399 - val_accuracy: 0.9058 - val_loss: 0.4466
Epoch 66/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9815 - loss: 0.0488 - val_accuracy: 0.8936 - val_loss: 0.5380
Epoch 67/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9831 - loss: 0.0405 - val_accuracy: 0.9103 - val_loss: 0.4667
Epoch 68/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9825 - loss: 0.0407 - val_accuracy: 0.9119 - val_loss: 0.5039
Epoch 69/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9848 - loss: 0.0402 - val_accuracy: 0.9058 - val_loss: 0.5149
Epoch 70/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9846 - loss: 0.0394 - val_accuracy: 0.8997 - val_loss: 0.4981
Epoch 71/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9787 - loss: 0.0485 - val_accuracy: 0.9088 - val_loss: 0.4902
Epoch 72/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9864 - loss: 0.0421 - val_accuracy: 0.9058 - val_loss: 0.5048
Epoch 73/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9824 - loss: 0.0430 - val_accuracy: 0.8982 - val_loss: 0.5092
Epoch 74/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9878 - loss: 0.0329 - val_accuracy: 0.9012 - val_loss: 0.5570
Epoch 75/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9868 - loss: 0.0350 - val_accuracy: 0.9073 - val_loss: 0.5218
Epoch 76/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9877 - loss: 0.0319 - val_accuracy: 0.9027 - val_loss: 0.5595
Epoch 77/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9840 - loss: 0.0410 - val_accuracy: 0.9164 - val_loss: 0.5190
Epoch 78/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9880 - loss: 0.0298 - val_accuracy: 0.9119 - val_loss: 0.5791
Epoch 79/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9880 - loss: 0.0324 - val_accuracy: 0.9073 - val_loss: 0.5959
Epoch 80/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9844 - loss: 0.0337 - val_accuracy: 0.9119 - val_loss: 0.5577
Epoch 81/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9859 - loss: 0.0343 - val_accuracy: 0.9134 - val_loss: 0.6208
Epoch 82/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9882 - loss: 0.0313 - val_accuracy: 0.9164 - val_loss: 0.5785
Epoch 83/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9881 - loss: 0.0345 - val_accuracy: 0.9027 - val_loss: 0.6170
Epoch 84/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9881 - loss: 0.0324 - val_accuracy: 0.8982 - val_loss: 0.6280
Epoch 85/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9908 - loss: 0.0276 - val_accuracy: 0.9073 - val_loss: 0.5877
Epoch 86/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9912 - loss: 0.0257 - val_accuracy: 0.9043 - val_loss: 0.6019
Epoch 87/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9909 - loss: 0.0273 - val_accuracy: 0.9134 - val_loss: 0.5739
Epoch 88/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9905 - loss: 0.0272 - val_accuracy: 0.8936 - val_loss: 0.6966
Epoch 89/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9868 - loss: 0.0348 - val_accuracy: 0.9179 - val_loss: 0.5867
Epoch 90/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9844 - loss: 0.0404 - val_accuracy: 0.9012 - val_loss: 0.6645
Epoch 91/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9877 - loss: 0.0323 - val_accuracy: 0.9179 - val_loss: 0.6313
Epoch 92/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9938 - loss: 0.0174 - val_accuracy: 0.9088 - val_loss: 0.6381
Epoch 93/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9917 - loss: 0.0203 - val_accuracy: 0.9073 - val_loss: 0.6749
Epoch 94/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9910 - loss: 0.0284 - val_accuracy: 0.9088 - val_loss: 0.6719
Epoch 95/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9929 - loss: 0.0219 - val_accuracy: 0.9058 - val_loss: 0.7331
Epoch 96/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9890 - loss: 0.0291 - val_accuracy: 0.8906 - val_loss: 0.8217
Epoch 97/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9911 - loss: 0.0221 - val_accuracy: 0.9119 - val_loss: 0.7355
Epoch 98/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9909 - loss: 0.0231 - val_accuracy: 0.9164 - val_loss: 0.6837
Epoch 99/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9907 - loss: 0.0267 - val_accuracy: 0.9103 - val_loss: 0.6678
Epoch 100/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9900 - loss: 0.0256 - val_accuracy: 0.9088 - val_loss: 0.8023
Epoch 101/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9932 - loss: 0.0181 - val_accuracy: 0.8967 - val_loss: 0.7638
Epoch 102/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9939 - loss: 0.0158 - val_accuracy: 0.9195 - val_loss: 0.7610
Epoch 103/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9931 - loss: 0.0185 - val_accuracy: 0.9119 - val_loss: 0.7933
Epoch 104/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9913 - loss: 0.0198 - val_accuracy: 0.9164 - val_loss: 0.7950
Epoch 105/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9869 - loss: 0.0289 - val_accuracy: 0.9134 - val_loss: 0.7688
Epoch 106/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9877 - loss: 0.0288 - val_accuracy: 0.9073 - val_loss: 0.8468
Epoch 107/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9882 - loss: 0.0264 - val_accuracy: 0.9179 - val_loss: 0.7303
Epoch 108/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9910 - loss: 0.0215 - val_accuracy: 0.9164 - val_loss: 0.7674
Epoch 109/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9885 - loss: 0.0273 - val_accuracy: 0.9043 - val_loss: 0.8013
Epoch 110/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9923 - loss: 0.0164 - val_accuracy: 0.9103 - val_loss: 0.7313
Epoch 111/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9941 - loss: 0.0201 - val_accuracy: 0.9088 - val_loss: 0.7496
Epoch 112/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9942 - loss: 0.0177 - val_accuracy: 0.9073 - val_loss: 0.7848
Epoch 113/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9895 - loss: 0.0294 - val_accuracy: 0.9179 - val_loss: 0.8727
Epoch 114/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9921 - loss: 0.0278 - val_accuracy: 0.9149 - val_loss: 0.7949
Epoch 115/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9916 - loss: 0.0254 - val_accuracy: 0.9149 - val_loss: 0.7723
Epoch 116/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9948 - loss: 0.0138 - val_accuracy: 0.9088 - val_loss: 0.8584
Epoch 117/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9922 - loss: 0.0211 - val_accuracy: 0.9119 - val_loss: 0.8352
Epoch 118/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9928 - loss: 0.0173 - val_accuracy: 0.9179 - val_loss: 0.9045
Epoch 119/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9904 - loss: 0.0341 - val_accuracy: 0.9134 - val_loss: 0.9136
Epoch 120/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9902 - loss: 0.0335 - val_accuracy: 0.9119 - val_loss: 0.7977
Epoch 121/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9911 - loss: 0.0198 - val_accuracy: 0.9073 - val_loss: 0.9280
Epoch 122/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9920 - loss: 0.0184 - val_accuracy: 0.9058 - val_loss: 0.9314
Epoch 123/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9919 - loss: 0.0163 - val_accuracy: 0.9195 - val_loss: 0.8703
Epoch 124/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9912 - loss: 0.0224 - val_accuracy: 0.9012 - val_loss: 0.9219
Epoch 125/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9912 - loss: 0.0210 - val_accuracy: 0.9195 - val_loss: 0.8979
Epoch 126/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9892 - loss: 0.0255 - val_accuracy: 0.9088 - val_loss: 0.8676
Epoch 127/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9941 - loss: 0.0190 - val_accuracy: 0.9134 - val_loss: 0.8405
Epoch 128/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0165 - val_accuracy: 0.9195 - val_loss: 0.9131
Epoch 129/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9938 - loss: 0.0177 - val_accuracy: 0.9073 - val_loss: 0.9294
Epoch 130/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9944 - loss: 0.0169 - val_accuracy: 0.9012 - val_loss: 0.9290
Epoch 131/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9925 - loss: 0.0197 - val_accuracy: 0.9103 - val_loss: 0.9934
Epoch 132/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9904 - loss: 0.0232 - val_accuracy: 0.9088 - val_loss: 0.8930
Epoch 133/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9936 - loss: 0.0199 - val_accuracy: 0.9119 - val_loss: 0.9324
Epoch 134/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9918 - loss: 0.0182 - val_accuracy: 0.9164 - val_loss: 0.9249
Epoch 135/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9875 - loss: 0.0229 - val_accuracy: 0.9012 - val_loss: 0.9589
Epoch 136/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9914 - loss: 0.0228 - val_accuracy: 0.8982 - val_loss: 0.9298
Epoch 137/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9888 - loss: 0.0276 - val_accuracy: 0.9149 - val_loss: 0.8997
Epoch 138/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9936 - loss: 0.0184 - val_accuracy: 0.9043 - val_loss: 0.9981
Epoch 139/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9904 - loss: 0.0217 - val_accuracy: 0.9179 - val_loss: 0.9532
Epoch 140/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9911 - loss: 0.0350 - val_accuracy: 0.9134 - val_loss: 0.9431
Epoch 141/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9899 - loss: 0.0203 - val_accuracy: 0.9179 - val_loss: 0.9969
Epoch 142/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9891 - loss: 0.0253 - val_accuracy: 0.9088 - val_loss: 1.0143
Epoch 143/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9921 - loss: 0.0179 - val_accuracy: 0.9164 - val_loss: 1.0111
Epoch 144/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9930 - loss: 0.0159 - val_accuracy: 0.9149 - val_loss: 0.9360
Epoch 145/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9933 - loss: 0.0186 - val_accuracy: 0.9088 - val_loss: 0.9268
Epoch 146/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9929 - loss: 0.0164 - val_accuracy: 0.9149 - val_loss: 0.9847
Epoch 147/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9943 - loss: 0.0137 - val_accuracy: 0.9103 - val_loss: 1.0281
Epoch 148/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9919 - loss: 0.0257 - val_accuracy: 0.9043 - val_loss: 1.0098
Epoch 149/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9947 - loss: 0.0147 - val_accuracy: 0.9119 - val_loss: 1.1175
Epoch 150/150
106/106 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9929 - loss: 0.0177 - val_accuracy: 0.9058 - val_loss: 1.0511

In [18]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.